# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # built in hooks from pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: d0293ebc40f6c0606d624ee4c638c7597f8044d2 # pragma: allowlist secret
    hooks:
      - id: check-yaml
        stages: [commit]
      - id: check-xml
        stages: [commit]
      - id: check-toml
        stages: [commit]
      - id: check-json
        stages: [commit]
      - id: check-added-large-files
        stages: [commit]
      - id: check-case-conflict
        stages: [commit]
      - id: check-illegal-windows-names
        stages: [commit]
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-shebang-scripts-are-executable
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
        # gitleaks and detect-secrets hooks
  - repo: https://github.com/gitleaks/gitleaks
    rev: 79cac73f7267f4a48f4bc73db11e105a6098a836 # pragma: allowlist secret
    hooks:
      - id: gitleaks
        stages: [commit]
  - repo: https://github.com/Yelp/detect-secrets
    rev: 52759b86b8e311a8ba0e8d464001b1bf353f54f8 # pragma: allowlist secret
    hooks:
      - id: detect-secrets
        stages: [commit]
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
  - repo: local
    hooks:
      - id: commit-lint
        name: commit-lint
        entry: pnpm commitlint
        language: system
        stages: [commit-msg]
      # lint only staged files. check lint-staged.config.js for more info
      # pointless since we need to lint java projects too
      # would require duplication but we'll use lint-affected instead
      # - id: lint-staged
      #   name: lint-staged
      #   entry: pnpm lint-staged
      #   pass_filenames: false
      #   language: system
      #   stages: [commit]
      - id: lint-affected
        name: lint-affected
        entry: pnpm lint-affected
        pass_filenames: false
        language: system
        stages: [commit]
      # full check before pushing to remote
      # to reduce probs of CI failing
      - id: lint-test-build-affected
        name: lint-test-build-affected
        entry: pnpm lint-test-build-affected
        verbose: true
        pass_filenames: false
        language: system
        stages: [push]
