# Composite private action to setup the CI environment with all the tools needed for the project.
# We could install pre-commit too here
name: Setup CI
runs:
  using: composite
  steps:
    - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
      name: Setup Java Step
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle Step
      uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3
      with:
        gradle-version: 8.7
